language: minimal
services:
  - docker
addons:
  hosts:
    - studio.localhost
script:
  - make configure SILENT=1 CONFIGURE_OPTS="-e SETTING_ACTIVATE_NOTES=1 -e SETTING_ACTIVATE_XQUEUE=1"
  - make build
  - make databases
  - make assets
  - make daemonize
  - until nc -w 3 localhost 80; do sleep 1; done
  - curl -If studio.localhost
  - curl -If localhost
  - docker-compose stop
deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && make push
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|release\/.*$
