language: minimal
services:
  - docker
script:
  - make configure SILENT=1 OPENEDX_RELEASE=hawthorn.2 CONFIGURE_OPTS="-e SETTING_ACTIVATE_NOTES=1 -e SETTING_ACTIVATE_XQUEUE=1"
  - make build
  - make databases
  #- make assets # too time-consuming
deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && make push
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|release\/.*$
